exports.clientPoInfo ={
  "id"            : "CPO1",
  "version"       : "001",
  "remark"        : "test",
  "startDate"     : "2017-08-01",
  "endDate"       : "",
  "creditTerm"    : 30,
  "description"   : "test",
  "country"       : "china",
  "city"          : "shanghai",
  "postCode"      : "0211",
  "address"       : "test",
  "year"          : "2017",
  "clientPoType"  : "Annual-Scope",
  "clientDetailId": "test-inv",
  "billToId"      : "test",
  "sentToId"      : "test",
  "placedToId"    : "test",
  "POFilePath"    : "test",
  "currencyId"    : "CNY",
  "GADUsr"        : "developer"
}

exports.clientInfo = {
  "id"          : "test2",
  "validDate"   : "2017-07-06",
  "code"        : "123",
  "nameEN"      : "test",
  "nameCN"      : "test",
  "location"    : "domestic",
  "INVType"     : "VAT",
  "description" : "test",
  "cartesisCode": "test",
  "creditTerm"  : "30",
  "contactName" : "test",
  "title"       : "test",
  "phoneNum"    : "123",
  "email"       : "test",
  "faxNum"      : "test",
  "logs":[],
  "approvers"   : [
  	{
  		"id"        : "test"
  	}
  ],
  "operation"   : "save"
}

exports.vendorInfo = {
  "validDate": "2017-10-13",
  "nameCN": "test",
  "nameEN": "test",
  "addressCN": "test",
  "addressEN": "test",
  "telephone": "13052029063",
  "fax": "test",
  "email": "test",
  "contactPerson": "test",
  "title": "test",
  "taxRate": 0,
  "expectedValue": 1000,
  "natureOfBusiness": "test",
  "referral": "test",
  "isVisit": "Y",
  "visitDate": "2017-10-10",
  "visitor": "test",
  "visitResult": "Satisfactory",
  "visitFilePath": "test",
  "capabilities": "test",
  "isConflict": "N",
  "conflictName": "test",
  "conflictTitle": "test",
  "relation": "test",
  "vendorCity": "test",
  "officeInChina": "test",
  "officeOutChina": "test",
  "vendorType": "Freelancer",
  "location":"domestic",
  "vendorFP":"Common",
  "COBC": "test",
  "BHD": "test",
  "NDA": "test",
  "BL": "test",
  "AL": "test",
  "remark": "test",
  "currencyId": "CNY",
  "vendorBanks": [
  	{
	  "companyName": "test",
	  "bankName": "test",
	  "bankAddress": "test",
	  "swiftCode": "test",
	  "accountAddress": "test",
	  "accountNum": "test",
	  "remark": "test",
	  "currencyId": "CNY"
	},
  	{
	  "companyName": "test",
	  "bankName": "test",
	  "bankAddress": "test",
	  "swiftCode": "test",
	  "accountAddress": "test",
	  "accountNum": "test",
	  "remark": "test",
	  "currencyId": "CNY"
	},
  ],
  "operation": "submit"
}

exports.DAFInfo = {
  "name": "test",
  "date": "2017-10-17",
  "purchaseType": "nonLowBid",
  "projectName": "project001",
  "description": "test",
  "team": "test",
  "budget": "test",
  "isWPP": "Y",
  "service": "test",
  "rationale": "test",
  "remark": "test",
  "clientDetailId": "test-vat",
  "JRId": "",
  "projectId": "project001",
  "GADUsr": "developer",
  "vendorDetailId": "vendor001",
  "currencyId": "CNY",
  "operation": "submit",
  "reasonIndexs":[
    "Timing",
    "ProjectContinuation",
  ]
}
